// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: cdc.proto

package cdcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CDCService_ListTopics_FullMethodName     = "/cdc.v1.CDCService/ListTopics"
	CDCService_GetTopic_FullMethodName       = "/cdc.v1.CDCService/GetTopic"
	CDCService_ListPartitions_FullMethodName = "/cdc.v1.CDCService/ListPartitions"
	CDCService_GetPartition_FullMethodName   = "/cdc.v1.CDCService/GetPartition"
	CDCService_GetMessages_FullMethodName    = "/cdc.v1.CDCService/GetMessages"
	CDCService_GetStats_FullMethodName       = "/cdc.v1.CDCService/GetStats"
	CDCService_HealthCheck_FullMethodName    = "/cdc.v1.CDCService/HealthCheck"
	CDCService_GetConfig_FullMethodName      = "/cdc.v1.CDCService/GetConfig"
)

// CDCServiceClient is the client API for CDCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
//	CDC Service — Kafka-UI–style APIs for the CDC queue system.
type CDCServiceClient interface {
	// Topics
	ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*TopicDetail, error)
	// Partitions
	ListPartitions(ctx context.Context, in *ListPartitionsRequest, opts ...grpc.CallOption) (*ListPartitionsResponse, error)
	GetPartition(ctx context.Context, in *GetPartitionRequest, opts ...grpc.CallOption) (*PartitionDetail, error)
	// Messages
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	// Stats / Health
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
}

type cDCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCDCServiceClient(cc grpc.ClientConnInterface) CDCServiceClient {
	return &cDCServiceClient{cc}
}

func (c *cDCServiceClient) ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, CDCService_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*TopicDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicDetail)
	err := c.cc.Invoke(ctx, CDCService_GetTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListPartitions(ctx context.Context, in *ListPartitionsRequest, opts ...grpc.CallOption) (*ListPartitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartitionsResponse)
	err := c.cc.Invoke(ctx, CDCService_ListPartitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetPartition(ctx context.Context, in *GetPartitionRequest, opts ...grpc.CallOption) (*PartitionDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitionDetail)
	err := c.cc.Invoke(ctx, CDCService_GetPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, CDCService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, CDCService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CDCService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, CDCService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CDCServiceServer is the server API for CDCService service.
// All implementations must embed UnimplementedCDCServiceServer
// for forward compatibility.
//
//	CDC Service — Kafka-UI–style APIs for the CDC queue system.
type CDCServiceServer interface {
	// Topics
	ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error)
	GetTopic(context.Context, *GetTopicRequest) (*TopicDetail, error)
	// Partitions
	ListPartitions(context.Context, *ListPartitionsRequest) (*ListPartitionsResponse, error)
	GetPartition(context.Context, *GetPartitionRequest) (*PartitionDetail, error)
	// Messages
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	// Stats / Health
	GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	mustEmbedUnimplementedCDCServiceServer()
}

// UnimplementedCDCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCDCServiceServer struct{}

func (UnimplementedCDCServiceServer) ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedCDCServiceServer) GetTopic(context.Context, *GetTopicRequest) (*TopicDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopic not implemented")
}
func (UnimplementedCDCServiceServer) ListPartitions(context.Context, *ListPartitionsRequest) (*ListPartitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPartitions not implemented")
}
func (UnimplementedCDCServiceServer) GetPartition(context.Context, *GetPartitionRequest) (*PartitionDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartition not implemented")
}
func (UnimplementedCDCServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedCDCServiceServer) GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedCDCServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCDCServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedCDCServiceServer) mustEmbedUnimplementedCDCServiceServer() {}
func (UnimplementedCDCServiceServer) testEmbeddedByValue()                    {}

// UnsafeCDCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CDCServiceServer will
// result in compilation errors.
type UnsafeCDCServiceServer interface {
	mustEmbedUnimplementedCDCServiceServer()
}

func RegisterCDCServiceServer(s grpc.ServiceRegistrar, srv CDCServiceServer) {
	// If the following call panics, it indicates UnimplementedCDCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CDCService_ServiceDesc, srv)
}

func _CDCService_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListTopics(ctx, req.(*ListTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetTopic(ctx, req.(*GetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListPartitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListPartitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListPartitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListPartitions(ctx, req.(*ListPartitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetPartition(ctx, req.(*GetPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CDCService_ServiceDesc is the grpc.ServiceDesc for CDCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CDCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdc.v1.CDCService",
	HandlerType: (*CDCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTopics",
			Handler:    _CDCService_ListTopics_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _CDCService_GetTopic_Handler,
		},
		{
			MethodName: "ListPartitions",
			Handler:    _CDCService_ListPartitions_Handler,
		},
		{
			MethodName: "GetPartition",
			Handler:    _CDCService_GetPartition_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _CDCService_GetMessages_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _CDCService_GetStats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CDCService_HealthCheck_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _CDCService_GetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdc.proto",
}

const (
	SinkConsumerService_CreateConsumer_FullMethodName = "/cdc.v1.SinkConsumerService/CreateConsumer"
	SinkConsumerService_ListConsumers_FullMethodName  = "/cdc.v1.SinkConsumerService/ListConsumers"
	SinkConsumerService_GetConsumer_FullMethodName    = "/cdc.v1.SinkConsumerService/GetConsumer"
	SinkConsumerService_DeleteConsumer_FullMethodName = "/cdc.v1.SinkConsumerService/DeleteConsumer"
	SinkConsumerService_PauseConsumer_FullMethodName  = "/cdc.v1.SinkConsumerService/PauseConsumer"
	SinkConsumerService_ResumeConsumer_FullMethodName = "/cdc.v1.SinkConsumerService/ResumeConsumer"
)

// SinkConsumerServiceClient is the client API for SinkConsumerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ── Sink Consumer Service ──────────────────────────────────
type SinkConsumerServiceClient interface {
	CreateConsumer(ctx context.Context, in *CreateConsumerRequest, opts ...grpc.CallOption) (*CreateConsumerResponse, error)
	ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error)
	GetConsumer(ctx context.Context, in *GetConsumerRequest, opts ...grpc.CallOption) (*ProtoConsumerStats, error)
	DeleteConsumer(ctx context.Context, in *DeleteConsumerRequest, opts ...grpc.CallOption) (*DeleteConsumerResponse, error)
	PauseConsumer(ctx context.Context, in *PauseConsumerRequest, opts ...grpc.CallOption) (*ProtoConsumerStats, error)
	ResumeConsumer(ctx context.Context, in *ResumeConsumerRequest, opts ...grpc.CallOption) (*ProtoConsumerStats, error)
}

type sinkConsumerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSinkConsumerServiceClient(cc grpc.ClientConnInterface) SinkConsumerServiceClient {
	return &sinkConsumerServiceClient{cc}
}

func (c *sinkConsumerServiceClient) CreateConsumer(ctx context.Context, in *CreateConsumerRequest, opts ...grpc.CallOption) (*CreateConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConsumerResponse)
	err := c.cc.Invoke(ctx, SinkConsumerService_CreateConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkConsumerServiceClient) ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumersResponse)
	err := c.cc.Invoke(ctx, SinkConsumerService_ListConsumers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkConsumerServiceClient) GetConsumer(ctx context.Context, in *GetConsumerRequest, opts ...grpc.CallOption) (*ProtoConsumerStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProtoConsumerStats)
	err := c.cc.Invoke(ctx, SinkConsumerService_GetConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkConsumerServiceClient) DeleteConsumer(ctx context.Context, in *DeleteConsumerRequest, opts ...grpc.CallOption) (*DeleteConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConsumerResponse)
	err := c.cc.Invoke(ctx, SinkConsumerService_DeleteConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkConsumerServiceClient) PauseConsumer(ctx context.Context, in *PauseConsumerRequest, opts ...grpc.CallOption) (*ProtoConsumerStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProtoConsumerStats)
	err := c.cc.Invoke(ctx, SinkConsumerService_PauseConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkConsumerServiceClient) ResumeConsumer(ctx context.Context, in *ResumeConsumerRequest, opts ...grpc.CallOption) (*ProtoConsumerStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProtoConsumerStats)
	err := c.cc.Invoke(ctx, SinkConsumerService_ResumeConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SinkConsumerServiceServer is the server API for SinkConsumerService service.
// All implementations must embed UnimplementedSinkConsumerServiceServer
// for forward compatibility.
//
// ── Sink Consumer Service ──────────────────────────────────
type SinkConsumerServiceServer interface {
	CreateConsumer(context.Context, *CreateConsumerRequest) (*CreateConsumerResponse, error)
	ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error)
	GetConsumer(context.Context, *GetConsumerRequest) (*ProtoConsumerStats, error)
	DeleteConsumer(context.Context, *DeleteConsumerRequest) (*DeleteConsumerResponse, error)
	PauseConsumer(context.Context, *PauseConsumerRequest) (*ProtoConsumerStats, error)
	ResumeConsumer(context.Context, *ResumeConsumerRequest) (*ProtoConsumerStats, error)
	mustEmbedUnimplementedSinkConsumerServiceServer()
}

// UnimplementedSinkConsumerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSinkConsumerServiceServer struct{}

func (UnimplementedSinkConsumerServiceServer) CreateConsumer(context.Context, *CreateConsumerRequest) (*CreateConsumerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConsumer not implemented")
}
func (UnimplementedSinkConsumerServiceServer) ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConsumers not implemented")
}
func (UnimplementedSinkConsumerServiceServer) GetConsumer(context.Context, *GetConsumerRequest) (*ProtoConsumerStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsumer not implemented")
}
func (UnimplementedSinkConsumerServiceServer) DeleteConsumer(context.Context, *DeleteConsumerRequest) (*DeleteConsumerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConsumer not implemented")
}
func (UnimplementedSinkConsumerServiceServer) PauseConsumer(context.Context, *PauseConsumerRequest) (*ProtoConsumerStats, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseConsumer not implemented")
}
func (UnimplementedSinkConsumerServiceServer) ResumeConsumer(context.Context, *ResumeConsumerRequest) (*ProtoConsumerStats, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeConsumer not implemented")
}
func (UnimplementedSinkConsumerServiceServer) mustEmbedUnimplementedSinkConsumerServiceServer() {}
func (UnimplementedSinkConsumerServiceServer) testEmbeddedByValue()                             {}

// UnsafeSinkConsumerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SinkConsumerServiceServer will
// result in compilation errors.
type UnsafeSinkConsumerServiceServer interface {
	mustEmbedUnimplementedSinkConsumerServiceServer()
}

func RegisterSinkConsumerServiceServer(s grpc.ServiceRegistrar, srv SinkConsumerServiceServer) {
	// If the following call panics, it indicates UnimplementedSinkConsumerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SinkConsumerService_ServiceDesc, srv)
}

func _SinkConsumerService_CreateConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkConsumerServiceServer).CreateConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkConsumerService_CreateConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkConsumerServiceServer).CreateConsumer(ctx, req.(*CreateConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkConsumerService_ListConsumers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsumersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkConsumerServiceServer).ListConsumers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkConsumerService_ListConsumers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkConsumerServiceServer).ListConsumers(ctx, req.(*ListConsumersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkConsumerService_GetConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkConsumerServiceServer).GetConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkConsumerService_GetConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkConsumerServiceServer).GetConsumer(ctx, req.(*GetConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkConsumerService_DeleteConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkConsumerServiceServer).DeleteConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkConsumerService_DeleteConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkConsumerServiceServer).DeleteConsumer(ctx, req.(*DeleteConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkConsumerService_PauseConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkConsumerServiceServer).PauseConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkConsumerService_PauseConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkConsumerServiceServer).PauseConsumer(ctx, req.(*PauseConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkConsumerService_ResumeConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkConsumerServiceServer).ResumeConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkConsumerService_ResumeConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkConsumerServiceServer).ResumeConsumer(ctx, req.(*ResumeConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SinkConsumerService_ServiceDesc is the grpc.ServiceDesc for SinkConsumerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SinkConsumerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdc.v1.SinkConsumerService",
	HandlerType: (*SinkConsumerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsumer",
			Handler:    _SinkConsumerService_CreateConsumer_Handler,
		},
		{
			MethodName: "ListConsumers",
			Handler:    _SinkConsumerService_ListConsumers_Handler,
		},
		{
			MethodName: "GetConsumer",
			Handler:    _SinkConsumerService_GetConsumer_Handler,
		},
		{
			MethodName: "DeleteConsumer",
			Handler:    _SinkConsumerService_DeleteConsumer_Handler,
		},
		{
			MethodName: "PauseConsumer",
			Handler:    _SinkConsumerService_PauseConsumer_Handler,
		},
		{
			MethodName: "ResumeConsumer",
			Handler:    _SinkConsumerService_ResumeConsumer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdc.proto",
}
